- src/envo/README.txt
if regex is not delimited by e.g. end of line, it would also match longer ids
> delimited regex

- src/envo/Makefile
See https://github.com/INCATools/ontology-development-kit/issues/50
@pbuttigieg - note that this has 2 commits, one adds the base module to the release folder (top level). This was built from the current envo-edit and doesn't correspond to the last release. I think it's OK to merge but if you want you can cherry pick the Makefile changes, just make sure to git add next release
> Adding base module

- src/envo/envo-idranges.owl
Addressing #733, I propose the following ID range additions for chemical_concentration and ebi_biomes design patterns, assigning them to id ranges 13 and 14 respectively.
> addition of id ranges for new design patterns

- src/envo/imports/chebi_import.owl
- src/envo/imports/chebi_terms.txt
Attempting to extend the CHEBI import for deep-sea manganese nodule fields.
The import routine didn't pull the class, however, even though it seems to be [available online](http://purl.obolibrary.org/obo/CHEBI_143901).
@cmungall any ideas?
> Refreshed CHEBI import for #770

- src/envo/envo-idranges.owl
Dear EnvO editor team, 
I would like to add this ID-range for myself, as cleared by @pbuttigieg. I've also fixed the numbering in the id-ranges file (which was one off).
I also noticed that there was an edit in the envo.owl file (https://github.com/EnvironmentOntology/envo/commit/56be01367a019edf1b0f7b60f98af2b4ef569d2b). @pbuttigieg I thought this was not to be edited directly. Could you please verify?
Best, 
@raissameyer
> Adding ID-range for @raissameyer

- src/envo/Makefile
- src/envo/reports/report_profile_edit.txt
We want to be flag any exact/label syn clashes as errors and block release﻿
> Adding additional strictness - exact/label checks

- src/envo/Makefile
Add this to the make file to replace `CRLF` with `LF`:
```
modules/%.owl: modules/%.csv patterns/%.yaml curie_map.yaml .FORCE
@perl -pe 's/\r\n/\n/' $< > $<.tmp && mv $<.tmp $< <------- added
dosdp-tools --table-format=csv --template=./patterns/$*.yaml --outfile=modules/$*.tmp.owl --obo-prefixes=true generate --infile=modules/$*.csv
$(ROBOT) annotate --input modules/$*.tmp.owl -O http://purl.obolibrary.org/obo/envo/modules/$*.owl --output modules/$*.owl && rm modules/$*.tmp.owl
```
I tested by changing `LF` to `CRLF` for csvs in in modules/*.csv. Then I ran the Makefile and checked to verify that the 'CRLF` was replaced by `LF`.
Interesting aside:  
In order for the Make to run, I had change where `generate` occurred in the dosdp-tools call.  
I changed:
```
dosdp-tools --table-format=csv …
```
> add functionality to replace CRLF in modules/*.csv with LF

- src/envo/Makefile
For our projects the UN Environment Working Group for SDG 14, I've created a subset for Plastics `envoPlastics` following the guidance on the corresponding [wiki page](https://github.com/EnvironmentOntology/envo/wiki/Making-a-new-subset), and @pbuttigieg's guidance [here](https://github.com/EnvironmentOntology/envo/issues/1085#issuecomment-816633363).
Please let me know if revisions are necessary.
> Adding envoPlastics subset

- src/envo/Makefile
Compiled from [Google Sheets robot template](https://docs.google.com/spreadsheets/d/1OQOtSlSjuw4OKre9YNE25-x9XnSNYaSPvbx_UjNZoBA/edit#gid=170789656)
See editor's notes for potential future improvements. I have used uppercase to indicate tasks that have been completed, like "ADDED 'composed primarily of' RO:0002473 mineral material 'ENVO:01000256'" on ENVO:03600011 'mineral horizon'
ontology ID | label
-- | --
ID | AL rdfs:label@en
ENVO:03600000 | cleanroom
ENVO:03600001 | contaminated sediment
ENVO:03600002 | cooling water
ENVO:03600003 | drinking water pipeline
ENVO:03600004 | drinking water treatment plant
ENVO:03600005 | electrical switch
ENVO:03600006 | food waste
ENVO:03600007 | formation fluid
ENVO:03600008 | intensive care unit
ENVO:03600009 | interstitial water
ENVO:03600010 | …
> Jagadish NMDC terms, without any makefile. #1089

- src/envo/imports/envo_bridge.owl
Fixes #1187
note once this is merged it will take a long time for the fix to propagate depending on the R0 rate for ontology infection
> Removing false injection

- src/envo/imports/foodon_import.obo
- src/envo/imports/foodon_import.owl
Fixes #1216 
@cmungall @kaiiam @pbuttigieg @turbomam   @ddooley 
I updated the `foodon` imports by running:
```
make imports/foodon_import.owl
make imports/foodon_import.obo
```
I checked the `envo-edit.owl` on my local branch. The orphaned `foodon` classes are not longer present.
> update foodon import

- src/envo/Makefile
> Tightening QC on ENVO CI

- src/envo/Makefile
- ignoring missing declaration warnings
- @wdduncan you were right, the problem was not with the edit file, it was with the PRE release file. I think with regards to your conversion issue, as crazy as it sounds, you may have to first convert to some other format like RDFXML and then convert back to OFN so the serialiser adds the declaration. Not sure though. In any case, this is one way this check works!
> Make sure DL profile check works

- src/envo/Makefile
> Create subset for Austrailian and New Zealand soil semantics

- .github/workflows/ontobot.yml
Each time an issue is created, the `ontobot.yml` workflow runs to see if there is a need for an intervention. If the issue has the phrase - "Hey ontobot, apply:" followed by bullets of KGCL commands. In response to such an issue, [`ontobot-change-agent` ](https://github.com/hrshdhgd/ontobot-change-agent) is invoked to make appropriate change suggetstions to the `src/ontology/envo-edit.owl` file and create a pull request linking itself to the original issue that triggered it.
An example: 
- Issue: https://github.com/hrshdhgd/envo/issues/1
- Associated PR: https://github.com/hrshdhgd/envo/pull/10
UPDATE: I've taken care of the above.
Attention: @cmungall
> Implement `ontobot-change-agent` as a GitHub action workflow

- src/envo/patterns/biome.yaml
- src/envo/patterns/ecosystem.yaml
This PR is picking up and will hopefully close multiple issues related to the biome hierarchy and semantics.
The approach used is to leverage a process class for ecological succession in climax communities. We acknowledge that the notion of climax communities is being refined in modern ecology, and have attempted to reflect this in the definitions and terminology (i.e. we do not content that any ecological community can ever reached an idealised climax state, but we do not that successional process can slow or maintain a community). 
We'll start with a desert example, get the pattern stable, and then propagate changes across terms (xref #1321)
> Addressing #865 with desert biome example

- src/envo/Makefile
This will reduce runtime and memory consumption to less than 8GB.
Note that someone needs to refresh the chebi and ncbitaxon imports on this branch and make sure that no terms needed by ENVO are lost.
> Switch NCBITAXON and CHEBI to slims

- .github/workflows/ontobot.yml
Previously we were downloading a standalone JAR file for `kgcl-java` which included robot. This required downloading robot which was redundant and not very efficient. ROBOT plugin usage is enabled as a feature since the latest release (v1.9.5) and this is packaged within the latest version of ODK (v1.4.3). 
This PR basically leverages those features and we only download the `kgcl-java` plugin JAR and use the robot that is available via ODK to use `kgcl-java` as. plugin and perform the same way as before.
**UPDATE**: Added a preliminary check for the phrase `Hey ontobot` in the issue body before running the whole workflow.
> Update `ontobot.yml` workflow to use `kgcl-java` as a plugin to robot that already exists in ODK.

- src/envo/imports/pato_import.owl
- src/envo/imports/pato_terms.txt
Per import process here: https://github.com/EnvironmentOntology/envo/wiki/Import-terms-from-other-ontologies - closes #1587
> Import PATO:'chronological age' 

- src/envo/robot_templates/nmdc_env_context_subset_membership.owl
- src/envo/robot_templates/nmdc_env_context_subset_membership.tsv
see
- https://github.com/microbiomedata/external-metadata-awareness/blob/main/claude_mds/nmdc-env-triad-valueset-lifecycle.md
> NMDC Sediment value set classes and assignments
