- src/envo/mappings/Makefile
- src/envo/sources/Makefile
- src/envo/sources/geonames.obo
somehow this ended up on the wrong branch - nothing to do with npo
> geonames mappings

- src/envo/envo-idranges.owl
created ID space for [Kai Blumberg](http://orcid.org/0000-0002-3410-4655) with @pbuttigieg.
> Added ID space

- src/envo/envo-edit.owl
@pbuttigieg I added neve and firn terms as a test, please review my changes.
> First independent pull request

- src/envo/envo-edit.owl
Added/refined classes for Arctic classes/environmental features and added several relevant processes.
> Second pull request for project cryophile

- src/envo/Makefile
- src/envo/imports/bfo_import.owl
> Fix bug whereby ro was used for bfo mirror

- src/envo/sparql/envoTableExport.sparql
- src/envo/sparql/envoTagsExport_long.sparql
consider to change the export format of the SPARQL query to TSV here: https://github.com/EnvironmentOntology/envo/blob/99a6f5c30daac88b2692aa4c7609f59f491b298f/src/envo/Makefile#L349
> add more sparql queries for export

- .travis.yml
> Use robot release rather than jenkins

- src/envo/imports/foodon_import.owl
> Regenerate foodon import

- src/envo/run.sh
This is copied over from go-ontology
> adding run.sh

- src/envo/catalog-v001.xml
- src/envo/modules/chemical_concentration.csv
- src/envo/modules/chemical_concentration.owl
- src/envo/patterns/chemical_concentration.yaml
> imports for chemical-concentration and fixing csv and yaml

- src/envo/Makefile
Hi !
I am currently working with @cmungall on improving the syntax and semantics of the OBO ontology language. This PR is an effort to standardize the syntax in `envo-edit.owl` so that the produced OBO is compliant with the [specification](http://owlcollab.github.io/oboformat/doc/obo-syntax.html).
The syntax compliance was checked with [althonos/fastobo](https://github.com/althonos/fastobo) which is an in-development parser and serializer for the OBO 1.4 format.
This is still work in progress, but I opened this issue as a place to discuss some of the requested modifications.
> [WIP] OBO format version 1.4 compliance

- src/envo/envo-idranges.owl
Assigning @rduerr an ID range for her incoming co-edits (#739)
> Adding ID range for @rduerr xref #739

- src/envo/envo-idranges.owl
Creating and ID range for Anne Thessen.
> Added ID range for @diatomsRcool

- src/envo/modules/ebi_biomes.csv
Due to merge conflicts, I will remake PR #736 here in to address PR #735 and issue #672.
> Remake PR #736 to fix ebi_biomes.csv

- src/envo/patterns/formation_of_environmental_feature.yaml
- src/envo/patterns/formation_of_material_entity.yaml
- src/envo/patterns/formation_of_material_entity_from_input.yaml
- src/envo/patterns/material_entity_formed_as_result_of.yaml
> First pass at DPs for formation processes

- src/envo/patterns/atmospheric_material_subtype.yaml
- src/envo/patterns/atmospheric_process_subtype.yaml
- src/envo/patterns/coastal_subtype_of_feature.yaml
- src/envo/patterns/soil_by_property.yaml
> Ready for review: new YAML files specifying existing implicit DPs

- src/envo/imports/ro_import.owl
- src/envo/imports/ro_terms.txt
Following on from #932 
Likely the beginning of an unplanned/planned environmental process pattern
> Changes linked to deforestation and planned deforestation

- src/envo/envo-idranges.owl
Adding an ID range, as discussed in #983﻿
> Adding an ID range for Lauren Chan

- src/envo/envo-idranges.owl
Dear EnvO editor team,
I would like to add this ID-range for myself as per recent discussion with @kaiiam and @pbuttigieg.  I'm interested in starting work on #1001 as well as mappings to SWEET (and perhaps GCMD).
\mm/
@brandonnodnarb
> Adding ID-range for @brandonnodnarb

- src/envo/imports/pato_import.owl
- src/envo/imports/pato_terms.txt
In this pull request (linked to #998), I'll revise the cloud genera definitions in ENVO and add axioms (importing new terms from PATO). 
We'll also need new qualities, which will either be requested on the PATO tracker or added to ENVO if 1) they are very environmentally specific, or 2) the requests are not addressed and released as this project approaches its end. In case of 2), I'll add the terms to ENVO and link them to the open PATO issue so the ENVO terms can be obsoleted and replaced by PATO terms in the future.
> Updating cloud genera #998

- src/envo/envo-idranges.owl
Creating an ID range for Jimena Linares (GFBIO e.V.)
> Added ID range for @mia-lg

- src/envo/imports/pato_import.obo
- src/envo/imports/pato_import.owl
- src/envo/imports/pato_terms.txt
PR for ESIP semantic harmonization meetings Oct-14 and Nov-18 2020. xref https://github.com/EnvironmentOntology/envo/issues/1028
> Issue 1028

- src/envo/envo-idranges.owl
Hi, 
pull request for issue #1077 to add ID-ranges for @meichen-liu and @iwilkie.
@pbuttigieg please let us know if anything should be out of order.
Thank you!
> added ID ranges for Mei-Chen Liu and Isabella Wilkie, see #1077

- src/envo/imports/chebi_import.obo
- src/envo/imports/chebi_import.owl
- src/envo/imports/chebi_terms.txt
- src/envo/imports/pato_import.owl
- src/envo/imports/pato_terms.txt
- src/envo/imports/sdgio_terms.txt
PR to add plastic-related PATO and CHEBI terms to ENVO
> Importing plastic-related PATO and CHEBI terms, Issue 1112

- src/envo/Makefile
Dear editors,
I have edited "foam" and "sea foam" as mentioned in issue #1134.
Thank you!
> Editing "foam" and "sea foam" - addressing issue #1134

- src/envo/Makefile
- src/envo/imports/go_import.owl
- src/envo/imports/go_terms.txt
Dear editors,
This PR is corresponding to issue #1152.
@pbuttigieg as ENVO currently doesn't have `eating behavior`, I added `ingestion` to `system process` for now ([see here](https://github.com/EnvironmentOntology/envo/issues/1152#issuecomment-838558029)). Please let me know if there are better solution.
Thank you!
> Added "ingestion", and "adsorption" - addressing issue #1152

- src/envo/envo-idranges.owl
Need ID_Range for open issues with [Agronomy issues](https://github.com/EnvironmentOntology/envo/projects/3) and to propose terms suited to ENVO, on an ongoing basis.
Requesting range of 300 terms.
closes #1222
> Add Agronomy ID_range #1222

- .github/workflows/qc.yml
This should fix the build issues with:
* #1172. 
* #1163
> Fix github actions to not build imports

- .gitignore
See also [NMDC-04_EnvO_template_robot_sheet](https://docs.google.com/spreadsheets/d/17yfrsNTiYk7XhYAQMJMYt7Is0RspLmZHu0WWpotIb9o/edit#gid=724193215)
> Issue #1193 Jagadish NMDC NTRs from 202100702

- src/envo/Makefile
> Added OWL DL profile check to CI

- src/envo/Makefile
This fix works, but after we have debated the problem on slack, we still don't know whats causing it.
In any case, it is safe to merge.
> Hot fixing the make pipeline

- src/envo/envo-idranges.owl
> Smaller NMDC id range... remainder for Mark and Alicia
